name: Deploy to Permaweb

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Deploy to Permaweb with On-Demand Payment
        run: |
          npx permaweb-deploy deploy \
            --arns-name argo \
            --deploy-folder dist \
            --sig-type arweave \
            --ario-process mainnet \
            --on-demand ario \
            --max-token-amount 2.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}